repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.1 # choose the version that works for your project
    hooks:
      - id: clang-format
        args: [--style=file] # use the .clang-format file in the root of the repository
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0 # choose the version that works for your project
    hooks:
      - id: yapf
        args: [--style=.style.yapf] # use the yapf config file in the root of the repository
